package com.mfg.paymentengine.service;

import com.mfg.paymentengine.api.dto.PaymentDtos.DirectDebitBatchRequest;
import com.mfg.paymentengine.api.dto.PaymentDtos.DirectDebitInstruction;
import com.mfg.paymentengine.api.dto.PaymentDtos.PaymentInstructionRequest;
import com.mfg.paymentengine.config.PaymentEngineProperties;
import com.mfg.paymentengine.domain.PaymentModels.*;
import com.mfg.paymentengine.error.ApiExceptionHandler.DomainConflictException;
import com.mfg.paymentengine.error.ApiExceptionHandler.DomainValidationException;
import com.mfg.paymentengine.service.Ports.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/** Unit tests. Traceability: MFG-ARC-PAY-CORE-001 v1.0 / AIF-165..AIF-174 / AC-001..AC-025. */
class PaymentWorkflowServiceTest {
    private PaymentRepository paymentRepository; private BatchRepository batchRepository; private IdempotencyStore idempotencyStore; private DomainEventPublisher eventPublisher; private ValidationEngine validationEngine; private SanctionsScreening sanctionsScreening; private FraudScoring fraudScoring; private Iso20022Broker iso20022Broker; private MandateManagement mandateManagement; private LiquidityManager liquidityManager; private SettlementAdapter settlementAdapter; private PaymentEngineProperties properties; private PaymentWorkflowService service;
    @BeforeEach void setUp() { paymentRepository = mock(PaymentRepository.class); batchRepository = mock(BatchRepository.class); idempotencyStore = mock(IdempotencyStore.class); eventPublisher = mock(DomainEventPublisher.class); validationEngine = mock(ValidationEngine.class); sanctionsScreening = mock(SanctionsScreening.class); fraudScoring = mock(FraudScoring.class); iso20022Broker = mock(Iso20022Broker.class); mandateManagement = mock(MandateManagement.class); liquidityManager = mock(LiquidityManager.class); settlementAdapter = mock(SettlementAdapter.class); properties = props(); service = new PaymentWorkflowService(paymentRepository, batchRepository, idempotencyStore, eventPublisher, validationEngine, sanctionsScreening, fraudScoring, iso20022Broker, mandateManagement, liquidityManager, settlementAdapter, properties); }
    @Test @DisplayName("createPayment should accept valid instant payment") void createPaymentShouldAcceptValidInstantPayment() { when(idempotencyStore.find("idem-1")).thenReturn(Optional.empty()); when(validationEngine.validate(any())).thenReturn(ValidationResult.ok()); when(sanctionsScreening.screen(any())).thenReturn(new DecisionResult(DecisionOutcome.ALLOW, "No match", 0)); when(fraudScoring.score(any())).thenReturn(new DecisionResult(DecisionOutcome.ALLOW, "Allowed", 100)); when(iso20022Broker.prepare(any())).thenReturn(new IsoMessage("pacs.008", "<xml/>")); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); var response = service.createPayment(PaymentRail.SCT_INST, validPayment("Example Merchant", new BigDecimal("25.50")), "idem-1", "MOBILE"); assertThat(response.paymentId()).startsWith("pay_"); assertThat(response.status()).isEqualTo(PaymentStatus.MESSAGE_READY.name()); assertThat(response.isoMessageType()).isEqualTo("pacs.008"); assertThat(response.idempotencyStatus()).isEqualTo("CREATED"); verify(idempotencyStore).store(anyString(), anyString(), anyString(), anyString()); }
    @Test @DisplayName("createPayment should replay existing payment") void createPaymentShouldReplayExistingPayment() { PaymentInstruction existing = payment("pay_123", "corr_123", PaymentRail.SCT_INST, PaymentStatus.MESSAGE_READY); PaymentInstructionRequest request = validPayment("Example Merchant", new BigDecimal("25.50")); when(idempotencyStore.find("idem-1")).thenReturn(Optional.of(new IdempotencyRecord("idem-1", fingerprint(PaymentRail.SCT_INST + ":" + request), "PAYMENT", "pay_123", Instant.now().plusSeconds(3600)))); when(paymentRepository.findById("pay_123")).thenReturn(Optional.of(existing)); var response = service.createPayment(PaymentRail.SCT_INST, request, "idem-1", "MOBILE"); assertThat(response.paymentId()).isEqualTo("pay_123"); assertThat(response.idempotencyStatus()).isEqualTo("REPLAYED"); verify(validationEngine, never()).validate(any()); }
    @Test @DisplayName("createPayment should reject idempotency conflict") void createPaymentShouldRejectIdempotencyConflict() { when(idempotencyStore.find("idem-1")).thenReturn(Optional.of(new IdempotencyRecord("idem-1", "different", "PAYMENT", "pay_123", Instant.now().plusSeconds(3600)))); assertThatThrownBy(() -> service.createPayment(PaymentRail.SCT_INST, validPayment("Example Merchant", new BigDecimal("25.50")), "idem-1", "MOBILE")).isInstanceOf(DomainConflictException.class); }
    @Test @DisplayName("createPayment should reject unsupported source") void createPaymentShouldRejectUnsupportedSource() { assertThatThrownBy(() -> service.createPayment(PaymentRail.SCT_INST, validPayment("Example Merchant", new BigDecimal("25.50")), "idem-1", "UNAPPROVED")).isInstanceOf(DomainValidationException.class); }
    @Test @DisplayName("validation failure should stop screening") void validationFailureShouldStopScreening() { when(idempotencyStore.find("idem-1")).thenReturn(Optional.empty()); when(validationEngine.validate(any())).thenReturn(ValidationResult.rejected("Invalid IBAN format")); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); assertThatThrownBy(() -> service.createPayment(PaymentRail.SCT_INST, validPayment("Example Merchant", new BigDecimal("25.50")), "idem-1", "MOBILE")).isInstanceOf(DomainValidationException.class); verify(sanctionsScreening, never()).screen(any()); }
    @Test @DisplayName("sanctions block should stop processing") void sanctionsBlockShouldStopProcessing() { when(idempotencyStore.find("idem-1")).thenReturn(Optional.empty()); when(validationEngine.validate(any())).thenReturn(ValidationResult.ok()); when(sanctionsScreening.screen(any())).thenReturn(new DecisionResult(DecisionOutcome.BLOCK, "Potential sanctions/watchlist match", 1000)); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); assertThatThrownBy(() -> service.createPayment(PaymentRail.SCT_INST, validPayment("Example Merchant", new BigDecimal("25.50")), "idem-1", "MOBILE")).isInstanceOf(DomainConflictException.class); verify(fraudScoring, never()).score(any()); }
    @Test @DisplayName("fraud block should stop ISO preparation") void fraudBlockShouldStopIsoPreparation() { when(idempotencyStore.find("idem-1")).thenReturn(Optional.empty()); when(validationEngine.validate(any())).thenReturn(ValidationResult.ok()); when(sanctionsScreening.screen(any())).thenReturn(new DecisionResult(DecisionOutcome.ALLOW, "No match", 0)); when(fraudScoring.score(any())).thenReturn(new DecisionResult(DecisionOutcome.BLOCK, "Fraud score exceeds block threshold", 950)); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); assertThatThrownBy(() -> service.createPayment(PaymentRail.SCT_INST, validPayment("High Risk Merchant", new BigDecimal("25000.00")), "idem-1", "MOBILE")).isInstanceOf(DomainConflictException.class); verify(iso20022Broker, never()).prepare(any()); }
    @Test @DisplayName("settlement should approve sufficient liquidity") void settlementShouldApproveSufficientLiquidity() { PaymentInstruction instruction = payment("pay_1", "corr_1", PaymentRail.SCT_INST, PaymentStatus.MESSAGE_READY); when(paymentRepository.findById("pay_1")).thenReturn(Optional.of(instruction)); when(liquidityManager.check(any())).thenReturn(new LiquidityDecision(true, "Liquidity approved")); when(settlementAdapter.submit(any(), any())).thenReturn(new SettlementResult("INSTANT_CSM", "ACSP", "ack_1")); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); var response = service.submitSettlement("pay_1", PaymentRail.SCT_INST); assertThat(response.settlementStatus()).isEqualTo("ACSP"); assertThat(response.settlementRoute()).isEqualTo("INSTANT_CSM"); }
    @Test @DisplayName("settlement should block insufficient liquidity") void settlementShouldBlockInsufficientLiquidity() { PaymentInstruction instruction = payment("pay_1", "corr_1", PaymentRail.SCT_INST, PaymentStatus.MESSAGE_READY); when(paymentRepository.findById("pay_1")).thenReturn(Optional.of(instruction)); when(liquidityManager.check(any())).thenReturn(new LiquidityDecision(false, "Insufficient liquidity")); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); assertThatThrownBy(() -> service.submitSettlement("pay_1", PaymentRail.SCT_INST)).isInstanceOf(DomainConflictException.class); verify(settlementAdapter, never()).submit(any(), any()); }
    @Test @DisplayName("exception event should process supported return") void exceptionEventShouldProcessSupportedReturn() { PaymentInstruction instruction = payment("pay_1", "corr_1", PaymentRail.SCT_INST, PaymentStatus.SETTLEMENT_ACCEPTED); when(paymentRepository.findById("pay_1")).thenReturn(Optional.of(instruction)); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); var response = service.handleExceptionEvent("pay_1", "RETURN", "AC01", "ext-1"); assertThat(response.status()).isEqualTo("PROCESSED"); assertThat(instruction.getStatus()).isEqualTo(PaymentStatus.RETURNED); }
    @Test @DisplayName("reconcile should identify matched and broken records") void reconcileShouldIdentifyMatchedAndBrokenRecords() { when(paymentRepository.findAll()).thenReturn(List.of(payment("pay_1", "corr_1", PaymentRail.SCT_INST, PaymentStatus.SETTLEMENT_ACCEPTED), payment("pay_2", "corr_2", PaymentRail.SCT_INST, PaymentStatus.RETURNED))); var response = service.reconcile("report-1", LocalDate.now()); assertThat(response.matchedCount()).isEqualTo(1); assertThat(response.breakCount()).isEqualTo(1); }
    @Test @DisplayName("report summary should aggregate totals") void reportSummaryShouldAggregateTotals() { PaymentInstruction p1 = payment("pay_1", "corr_1", PaymentRail.SCT_INST, PaymentStatus.SETTLEMENT_ACCEPTED); p1.setAmount(new BigDecimal("10.00")); PaymentInstruction p2 = payment("pay_2", "corr_2", PaymentRail.SCT_INST, PaymentStatus.RETURNED); p2.setAmount(new BigDecimal("20.00")); when(paymentRepository.findAll()).thenReturn(List.of(p1, p2)); var summary = service.reportSummary(); assertThat(summary.totalPayments()).isEqualTo(2); assertThat(summary.totalAmount()).isEqualByComparingTo("30.00"); }
    @Test @DisplayName("direct debit batch should partially accept") void directDebitBatchShouldPartiallyAccept() { DirectDebitBatchRequest request = new DirectDebitBatchRequest("corp-1", "batch-ref-1", LocalDate.now().plusDays(1), List.of(new DirectDebitInstruction("instr-1", "MANDATE123", "DE89370400440532013000", "FR1420041010050500013M02606", "Debtor One", new BigDecimal("15.00"), "EUR"), new DirectDebitInstruction("instr-2", "INVALID-MANDATE", "DE89370400440532013000", "FR1420041010050500013M02606", "Debtor Two", new BigDecimal("25.00"), "EUR"))); when(idempotencyStore.find("batch-idem-1")).thenReturn(Optional.empty()); when(mandateManagement.isMandateValid(anyString(), anyString(), anyString())).thenAnswer(i -> !String.valueOf(i.getArgument(0)).contains("INVALID")); when(validationEngine.validate(any())).thenReturn(ValidationResult.ok()); when(sanctionsScreening.screen(any())).thenReturn(new DecisionResult(DecisionOutcome.ALLOW, "No match", 0)); when(iso20022Broker.prepare(any())).thenReturn(new IsoMessage("pacs.003", "<xml/>")); when(paymentRepository.save(any())).thenAnswer(i -> i.getArgument(0)); when(batchRepository.save(any())).thenAnswer(i -> i.getArgument(0)); var response = service.createDirectDebitBatch(request, "batch-idem-1", "CORPORATE"); assertThat(response.status()).isEqualTo("PARTIALLY_ACCEPTED"); assertThat(response.acceptedCount()).isEqualTo(1); assertThat(response.rejectedCount()).isEqualTo(1); }
    private PaymentInstructionRequest validPayment(String creditorName, BigDecimal amount) { return new PaymentInstructionRequest("DE89370400440532013000", "FR1420041010050500013M02606", creditorName, amount, "EUR", "Invoice 123"); }
    private PaymentInstruction payment(String paymentId, String correlationId, PaymentRail rail, PaymentStatus status) { PaymentInstruction instruction = new PaymentInstruction(); instruction.setPaymentId(paymentId); instruction.setCorrelationId(correlationId); instruction.setRail(rail); instruction.setStatus(status); instruction.setDebtorIban("DE89370400440532013000"); instruction.setCreditorIban("FR1420041010050500013M02606"); instruction.setCreditorName("Example Merchant"); instruction.setAmount(new BigDecimal("25.50")); instruction.setCurrency("EUR"); instruction.setIsoMessageType("pacs.008"); return instruction; }
    private String fingerprint(String value) { return org.springframework.util.DigestUtils.md5DigestAsHex(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)); }
    private PaymentEngineProperties props() { return new PaymentEngineProperties(new PaymentEngineProperties.Security(false, List.of("MOBILE", "WEB", "CORPORATE", "PSD2", "TPP", "B2B")), new PaymentEngineProperties.Idempotency(24), new PaymentEngineProperties.Screening(List.of("SANCTIONED", "BLOCKED")), new PaymentEngineProperties.Fraud(900, 700), new PaymentEngineProperties.Liquidity(new BigDecimal("10000000")), new PaymentEngineProperties.Traceability("MFG-ARC-PAY-CORE-001", "v1.0", "1783915119965/MFG-Architecture-6page.docx")); }
}
