package com.mfg.paymentengine.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mfg.paymentengine.api.dto.PaymentDtos.*;
import com.mfg.paymentengine.config.PaymentEngineProperties;
import com.mfg.paymentengine.error.ApiExceptionHandler;
import com.mfg.paymentengine.infra.DefaultComponentAdapters;
import com.mfg.paymentengine.infra.InMemoryAdapters;
import com.mfg.paymentengine.service.PaymentWorkflowService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/** Automation API tests. Traceability: TC-PE-001..TC-PE-010 / AC-001..AC-025. */
class PaymentControllerAutomationTest {
    private final ObjectMapper objectMapper = new ObjectMapper().findAndRegisterModules(); private MockMvc mockMvc;
    @BeforeEach void setUp() { PaymentEngineProperties p = props(); PaymentWorkflowService service = new PaymentWorkflowService(new InMemoryAdapters.InMemoryPaymentRepository(), new InMemoryAdapters.InMemoryBatchRepository(), new InMemoryAdapters.InMemoryIdempotencyStore(p), new DefaultComponentAdapters.LoggingDomainEventPublisher(), new DefaultComponentAdapters.DefaultValidationEngine(), new DefaultComponentAdapters.DefaultSanctionsScreening(p), new DefaultComponentAdapters.DefaultFraudScoring(p), new DefaultComponentAdapters.DefaultIso20022Broker(), new DefaultComponentAdapters.DefaultMandateManagement(), new DefaultComponentAdapters.DefaultLiquidityManager(p), new DefaultComponentAdapters.DefaultSettlementAdapter(), p); mockMvc = MockMvcBuilders.standaloneSetup(new PaymentController(service)).setControllerAdvice(new ApiExceptionHandler()).build(); }
    @Test @DisplayName("Instant payment should be accepted") void instantPaymentShouldBeAccepted() throws Exception { mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-001").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()).andExpect(jsonPath("$.paymentId").exists()).andExpect(jsonPath("$.traceability.source_doc_id").value("MFG-ARC-PAY-CORE-001")); }
    @Test @DisplayName("Duplicate instant payment should replay") void duplicateInstantPaymentShouldReplay() throws Exception { var first = mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-003").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()).andReturn(); var second = mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-003").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()).andReturn(); JsonNode firstJson = objectMapper.readTree(first.getResponse().getContentAsString()); JsonNode secondJson = objectMapper.readTree(second.getResponse().getContentAsString()); assertThat(secondJson.get("idempotencyStatus").asText()).isEqualTo("REPLAYED"); assertThat(secondJson.get("paymentId").asText()).isEqualTo(firstJson.get("paymentId").asText()); }
    @Test @DisplayName("Batch SDD should be partially accepted") void batchSddShouldBePartiallyAccepted() throws Exception { mockMvc.perform(post("/v1/payments/direct-debit/batches").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "batch-001").header("X-Source-Channel", "CORPORATE").content(objectMapper.writeValueAsString(validBatch()))).andExpect(status().isAccepted()).andExpect(jsonPath("$.status").value("PARTIALLY_ACCEPTED")).andExpect(jsonPath("$.acceptedCount").value(1)).andExpect(jsonPath("$.rejectedCount").value(1)); }
    @Test @DisplayName("Settlement should succeed") void settlementShouldSucceed() throws Exception { var created = mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-007").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()).andReturn(); JsonNode createdJson = objectMapper.readTree(created.getResponse().getContentAsString()); mockMvc.perform(post("/v1/payments/" + createdJson.get("paymentId").asText() + "/settlement").contentType(MediaType.APPLICATION_JSON).content(objectMapper.writeValueAsString(new SettlementRequest("SCT_INST")))).andExpect(status().isOk()).andExpect(jsonPath("$.settlementStatus").value("ACSP")); }
    @Test @DisplayName("Exception event should update payment status") void supportedExceptionEventShouldUpdatePaymentStatus() throws Exception { var created = mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-009").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()).andReturn(); JsonNode createdJson = objectMapper.readTree(created.getResponse().getContentAsString()); mockMvc.perform(post("/v1/payments/exceptions").contentType(MediaType.APPLICATION_JSON).content(objectMapper.writeValueAsString(new ExceptionEventRequest(createdJson.get("paymentId").asText(), "RETURN", "AC01", "ext-001")))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("PROCESSED")); }
    @Test @DisplayName("Reconciliation and reporting should expose summaries") void reconciliationAndReportingShouldExposeSummaries() throws Exception { mockMvc.perform(post("/v1/payments/instant").contentType(MediaType.APPLICATION_JSON).header("Idempotency-Key", "idem-inst-010").header("X-Source-Channel", "MOBILE").content(objectMapper.writeValueAsString(validInstantPayment()))).andExpect(status().isAccepted()); mockMvc.perform(post("/v1/payments/reconciliation/run").contentType(MediaType.APPLICATION_JSON).content(objectMapper.writeValueAsString(new ReconciliationRequest("report-001", LocalDate.now())))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("COMPLETED")); mockMvc.perform(get("/v1/payments/reports/summary")).andExpect(status().isOk()).andExpect(jsonPath("$.totalPayments").exists()); }
    private PaymentInstructionRequest validInstantPayment() { return new PaymentInstructionRequest("DE89370400440532013000", "FR1420041010050500013M02606", "Example Merchant", new BigDecimal("25.50"), "EUR", "Invoice 123"); }
    private DirectDebitBatchRequest validBatch() { return new DirectDebitBatchRequest("corp-1", "batch-ref-1", LocalDate.now().plusDays(1), List.of(new DirectDebitInstruction("instr-1", "MANDATE123", "DE89370400440532013000", "FR1420041010050500013M02606", "Debtor One", new BigDecimal("15.00"), "EUR"), new DirectDebitInstruction("instr-2", "INVALID-MANDATE", "DE89370400440532013000", "FR1420041010050500013M02606", "Debtor Two", new BigDecimal("25.00"), "EUR"))); }
    private PaymentEngineProperties props() { return new PaymentEngineProperties(new PaymentEngineProperties.Security(false, List.of("MOBILE", "WEB", "CORPORATE", "PSD2", "TPP", "B2B")), new PaymentEngineProperties.Idempotency(24), new PaymentEngineProperties.Screening(List.of("SANCTIONED", "BLOCKED")), new PaymentEngineProperties.Fraud(900, 700), new PaymentEngineProperties.Liquidity(new BigDecimal("10000000")), new PaymentEngineProperties.Traceability("MFG-ARC-PAY-CORE-001", "v1.0", "1783915119965/MFG-Architecture-6page.docx")); }
}
